heat_template_version: 2013-05-23

description: A simple auto scaling group.

parameters:
  key:
    type: string
    description: keypair to enable SSH access to the instance.
    default: dtrishkin-key

  image:
    type: string
    description: ID of the image to use for the instance to be created.
    default: Ubuntu_14.04

  private_network:
    type: string
    label: Private network name or ID
    description: Network to attach instance to.
    default: heat-testing-net

  volume_size:
    type: number
    description: Size of volume to attach to instance
    default: 1
    constraints:
      - range: {min: 1, max: 10}

  instance_type:
    type: string
    description: Type of the instance to be created.
    default: m1.small

resources:
  group_of_nodes:
    type: OS::Heat::AutoScalingGroup
    properties:
      cooldown: 60
      desired_capacity: 3
      max_size: 5
      min_size: 1
      resource:
        type: "nova-server-instance-os-with-cinder.yaml"
        properties:
          key: {get_param: key}
          image: {get_param: image}
          private_network: {get_param: private_network}
          vol_size: {get_param: volume_size}
          flavor: {get_param: instance_type}

  scale_up_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: group_of_nodes}
      cooldown: 60
      scaling_adjustment: 1

  scale_down_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: group_of_nodes}
      cooldown: 60
      scaling_adjustment: '-1'

  cpu_alarm_high:
    type: OS::Ceilometer::Alarm
    properties:
      meter_name: cpu_util
      statistic: avg
      period: 60
      evaluation_periods: 1
      threshold: 50
      alarm_actions:
        - {get_attr: [scale_up_policy, alarm_url]}
      comparison_operator: gt

  cpu_alarm_low:
    type: OS::Ceilometer::Alarm
    properties:
      meter_name: cpu_util
      statistic: avg
      period: 600
      evaluation_periods: 1
      threshold: 15
      alarm_actions:
        - {get_attr: [scale_down_policy, alarm_url]}
      comparison_operator: lt

outputs:
  scale_up_url:
    description: >
      This URL is the webhook to scale up the group.  You can invoke
      the scale-up operation by doing an HTTP POST to this URL; no
      body nor extra headers are needed.
    value: {get_attr: [scale_up_policy, alarm_url]}
  scale_down_url:
    description: >
      This URL is the webhook to scale down the group.  You can invoke
      the scale-down operation by doing an HTTP POST to this URL; no
      body nor extra headers are needed.
    value: {get_attr: [scale_down_policy, alarm_url]}
  node_group_size:
    description: >
      This is the current size of the auto scaling group.
    value: {get_attr: [group_of_nodes, current_size]}
  server_list:
    description: >
      This is a list of server names that are part of the group.
    value: {get_attr: [group_of_nodes, outputs_list, name]}
  networks:
    description: >
      This is a map of server resources and their networks.
    value: {get_attr: [group_of_nodes, outputs, networks]}
  server_ip_ads:
    description: >
      This is a list of first ip addresses of the servers in the group
      for a specified network.
    value: {get_attr: [group_of_nodes, outputs_list, networks, {get_param: network}, 0]}