heat_template_version: 2013-05-23

description: >
  Example of using ResourceGroup to attach multiple volumes to an instance

parameters:
  key:
    type: string
    description: keypair to enable SSH access to the instance.
    default: dtrishkin-key

  image:
    type: string
    description: ID of the image to use for the instance to be created.
    default: Ubuntu_14.04

  private_network:
    type: string
    label: Private network name or ID
    description: Network to attach instance to.
    default: heat-testing-net

  volume_size:
    type: number
    description: Size of volume to attach to instance
    default: 1
    constraints:
      - range: {min: 1, max: 10}

  num_volumes:
    type: number
    description: Number of volumes to attach to instance
    default: 2
    constraints:
      - range: {min: 1, max: 10}

  instance_type:
    type: string
    description: Type of the instance to be created.
    default: m1.small

resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: instance_type }
      key_name: { get_param: key }
      networks:
        - network: { get_param: private_network }
      user_data_format: RAW
      user_data:
        adduser --disabled-password --gecos "" ubuntu

  group_of_volumes:
    type: OS::Heat::ResourceGroup
    properties:
      count: {get_param: num_volumes}
      resource_def:
        type: volume_with_attachment.yaml
        properties:
          instance_id: {get_resource: my_instance}
          volume_size: {get_param: volume_size}
